# Generated by Django 5.1.1 on 2024-09-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chip', '0002_alter_chip_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chip',
            new_name='ChipModel',
        ),
    ]
