# Generated by Django 5.1.1 on 2024-10-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chip', '0003_rename_chip_chipmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chipmodel',
            old_name='name',
            new_name='quantity',
        ),
    ]
