# Generated by Django 5.1.1 on 2024-10-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chip', '0004_rename_name_chipmodel_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chipmodel',
            old_name='quantity',
            new_name='denomination',
        ),
    ]
