# Generated by Django 5.1.1 on 2024-10-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip', '0007_alter_chipmodel_denomination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipmodel',
            name='denomination',
            field=models.FloatField(),
        ),
    ]
