# Generated by Django 5.1.1 on 2024-11-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillcredit',
            name='action_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
