# Generated by Django 5.1.1 on 2024-11-24 23:01

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_fillcredit_action_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillcredit',
            name='created_at',
            field=models.DateTimeField(default=transactions.models.adjusted_now),
        ),
    ]
