# Generated by Django 5.1.1 on 2024-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotmachine',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
