# Generated by Django 5.1.1 on 2024-10-03 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_machine', '0002_alter_slotmachine_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='slotmachine',
            name='bvbMoney',
        ),
        migrations.CreateModel(
            name='DailyAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('slot_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_amounts', to='slot_machine.slotmachine')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_amounts_by_date', to='slot_machine.gameday')),
                ('game_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_amounts_by_game_day', to='slot_machine.gameday')),
            ],
        ),
        migrations.AddField(
            model_name='slotmachine',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slot_machines', to='slot_machine.hall'),
        ),
    ]
