# Generated by Django 5.1.1 on 2024-10-03 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot_machine', '0003_gameday_hall_remove_slotmachine_bvbmoney_dailyamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotmachine',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_machines', to='slot_machine.hall'),
        ),
    ]
