# Generated by Django 5.1.1 on 2024-10-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot_machine', '0004_alter_slotmachine_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyamount',
            name='date',
        ),
    ]
