# Generated by Django 5.1.1 on 2024-11-07 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('open_flot_total', models.FloatField(default=0.0)),
                ('result', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_edited', models.DateTimeField(blank=True, null=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('open_flot', models.JSONField(default=dict)),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_table.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Plaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('plaques_total', models.FloatField(default=0.0)),
                ('result', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('plaques', models.JSONField(default=dict)),
                ('game_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_table.gameday')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_table.table')),
            ],
        ),
        migrations.CreateModel(
            name='CloseFloot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('close_flot_total', models.FloatField(default=0.0)),
                ('fill_credit', models.FloatField(default=0.0)),
                ('result', models.FloatField(default=0.0)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('close_flot', models.JSONField(default=dict)),
                ('game_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_table.gameday')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_table.table')),
            ],
        ),
        migrations.CreateModel(
            name='TableResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('game_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_table.gameday')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_table.table')),
            ],
        ),
    ]
