# Generated by Django 5.1.1 on 2024-11-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameDay',
            new_name='GameDayLive',
        ),
    ]
