# Generated by Django 5.1.1 on 2024-10-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0002_rename_open_flot_result_table_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
