# Generated by Django 5.1.1 on 2024-11-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0003_alter_plaque_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plaque',
            options={'verbose_name': 'Plaque', 'verbose_name_plural': 'Plaques'},
        ),
    ]
