# Generated by Django 5.1.1 on 2024-10-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0004_hall_table_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='hall',
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
    ]
