# Generated by Django 5.1.1 on 2024-11-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0004_alter_plaque_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plaque',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='plaque',
            unique_together=set(),
        ),
    ]
