# Generated by Django 5.1.1 on 2024-11-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0006_fillcredit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FillCredit',
        ),
    ]
