# Generated by Django 5.1.1 on 2024-10-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0006_hall_table_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closefloot',
            name='game_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_table.gameday'),
        ),
    ]
