# Generated by Django 5.1.1 on 2024-10-22 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0007_alter_closefloot_game_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closefloot',
            name='game_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game_table.gameday'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_table.hall'),
        ),
    ]
