# Generated by Django 5.1.1 on 2024-10-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0005_closefloot_result'),
        ('game_table', '0008_alter_closefloot_game_day_alter_table_hall'),
    ]

    operations = [
    ]
