# Generated by Django 5.1.1 on 2024-11-21 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0009_alter_table_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='game_table.hall'),
        ),
    ]
