# Generated by Django 5.1.1 on 2024-10-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0009_merge_20241031_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='closefloot',
            name='fill_credit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='closefloot',
            name='plaques',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='closefloot',
            name='plaques_total',
            field=models.FloatField(default=0.0),
        ),
    ]
