# Generated by Django 5.1.1 on 2024-10-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0010_closefloot_fill_credit_closefloot_plaques_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closefloot',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
