# Generated by Django 5.1.1 on 2024-11-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0010_alter_table_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closefloot',
            old_name='fill_credit',
            new_name='total_credit',
        ),
        migrations.AddField(
            model_name='closefloot',
            name='total_fill',
            field=models.FloatField(default=0.0),
        ),
    ]
