# Generated by Django 5.1.1 on 2024-11-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0011_rename_fill_credit_closefloot_total_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closefloot',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plaque',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
