# Generated by Django 5.1.1 on 2024-10-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0011_closefloot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closefloot',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
