# Generated by Django 5.1.1 on 2024-11-05 08:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0012_alter_closefloot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closefloot',
            name='plaques',
        ),
        migrations.RemoveField(
            model_name='closefloot',
            name='plaques_total',
        ),
        migrations.CreateModel(
            name='Plaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('plaques_total', models.FloatField(default=0.0)),
                ('result', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('plaques', models.JSONField(default=dict)),
                ('game_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_table.gameday')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_table.table')),
            ],
        ),
    ]
