# Generated by Django 5.1.1 on 2024-11-06 09:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_table', '0013_remove_closefloot_plaques_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('game_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_table.gameday')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_table.table')),
            ],
        ),
    ]
